### ISSUE TITLE
Oct 2 Meetup

### ISSUE THREAD

**Issue by nateroling** [dubuque/meta#3]
## Agenda
* Create github pages site explaining the Dubuque Developers group.
* Invite people to Oct 28th [DevOps Meetup](http://www.meetup.com/techcorridorio/events/225569208/?fromEmail=225569208&rv=ea1)

## Ideas
* Collect list of local meetups
* Decide on areas - how far out?
* Collect list of regional conferences
* Start list of talks we could watch
* Start list of technologies to cover
* Discuss goals/mission
* Find resources on building a community
* Discuss communications channels
  * meetup.com
  * slack - #dubuque on techcorridor
  * facebook group
  * github
* Local support
  * Library
  * Colleges
* Venues
  * Monk's
  * Jubeck's
  * Inspire

## Group Goals
* Organize trips to regional meetups
  * Cedar Rapids
  * Iowa City
  * Madison

**Comment by killswitch** [comment]
Potential meetups we can attend together:

* http://www.meetup.com/MadisonJS/
* http://www.meetup.com/madisonphp/
* http://www.meetup.com/Northern-IL-Coders/
* http://www.meetup.com/Madison-Hack-and-Tell/
* http://www.meetup.com/Docker-Madison/
* http://www.meetup.com/UX-Iowa/
* http://www.meetup.com/Madison-Devops/
